# name: Deploy Frontend

# on:
#   push:
#     branches:
#       - main  # ou outra branch de produÃ§Ã£o

# jobs:
#   deploy-frontend:
#     name: Deploy frontend to Cloudflare Workers
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: apps/frontend

#     steps:
#       - name: ğŸ“¦ Checkout repositÃ³rio
#         uses: actions/checkout@v3

#       - name: ğŸ”§ Instalar PNPM
#         uses: pnpm/action-setup@v2
#         with:
#           version: 8

#       - name: ğŸ§° Instalar Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 20
#           cache: 'pnpm'

#       - name: ğŸ“¥ Instalar dependÃªncias
#         run: pnpm install

#       - name: ğŸ› ï¸ Build do frontend
#         run: pnpm build
#         env:
#             PUBLIC_API_URL: https://backend-production.joaosantana-ti.workers.dev/

#       - name: ğŸš€ Instalar Wrangler globalmente
#         run: npm install -g wrangler@4

#       - name: ğŸ” Mostrar versÃ£o do Wrangler
#         run: wrangler --version

#       - name: ğŸš€ Deploy com Wrangler (Cloudflare Workers)
#         run: wrangler deploy
#         env:
#           CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
#           CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

